version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb-dev
    hostname: mariadb
    volumes:
      - /var/lib/mysql-dev:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: deogells/glpi-mirante
    container_name : glpi-dev
    hostname: glpi
    ports:
      - "8082:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi-dev/:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Fortaleza
    restart: always
